export const Approximations = {
	LINEAR: 'LINEAR',
	QUADRATIC: 'QUADRATIC',
	EXPONENTIAL: 'EXPONENTIAL',
	POTENTIAL: 'POTENTIAL',
	HYPERBOLIC: 'HYPERBOLIC'
};

export const Data = {
	INTERMEDIATE: 'INTERMEDIATE',
	COMPARISON: 'COMPARISON'
};
